import sizesJson from './sizes.json';

/**
 * Intrinsic pixel dimensions of everything under public/images, keyed by public
 * path. Generated by `npm run optimize:images` — do not edit sizes.json by hand.
 */
const sizes = sizesJson as Record<string, [number, number]>;

/**
 * width/height attributes for an image, or nothing if it is not in the manifest.
 *
 * Spread onto an `<img>`: they give the browser an aspect ratio to reserve space
 * with before the bytes arrive, which is what stops the galleries reflowing as
 * they load. CSS still decides the rendered size, so `w-full h-auto` keeps
 * working unchanged.
 *
 * A miss is normal and non-fatal — the CMS can reference an image the optimizer
 * has not walked yet — and just means that one image behaves as it does today.
 */
export function imageSize(src?: string | null): { width: number; height: number } | Record<string, never> {
  if (!src) return {};
  const found = sizes[src];
  return found ? { width: found[0], height: found[1] } : {};
}
