import srcsetJson from './srcset.json';

/**
 * Precomputed `srcset` strings for images that have responsive siblings, keyed
 * by public path. Generated by `npm run optimize:images` — do not edit
 * srcset.json by hand. An image not in here (a logo, an icon, anything already
 * small) simply renders its plain `src` with no srcset, which is correct.
 */
const srcsets = srcsetJson as Record<string, string>;

export function imageSrcset(src?: string | null): { srcset: string; sizes: string } | Record<string, never> {
  if (!src) return {};
  const found = srcsets[src];
  return found ? { srcset: found, sizes: '100vw' } : {};
}
